% This section initializes the database.
% New registrations are appended to the end of the list.
% This data much run first 


existData = { ...
   {'U0001', 'John Peter', '3343434423', 'Toronto', struct('name', 'Apple iPhone X', 'category', 'Electronics', 'price', '340', 'condition', 'Fair', 'location', 'Toronto', 'description', '64GB, minor scratches.')}; ...
   {'U0002', 'Emma Smith', '7781234567', 'Ottawa', struct('name', 'Leather Jacket', 'category', 'Clothing', 'price', '50', 'condition', 'Good', 'location', 'Ottawa', 'description', 'Black, size M, barely used.')}; ...
   {'U0003', 'Noah Wilson', '6479876543', 'Markham', struct('name', 'Wooden Dining Table', 'category', 'Furniture', 'price', '200', 'condition', 'Excellent', 'location', 'Markham', 'description', 'Seats 6, dark oak, barely used.')}; ...
   {'U0004', 'Sophia Brown', '5142345678', 'Ottawa', struct('name', 'Car Tire Set', 'category', 'Auto Care', 'price', '120', 'condition', 'Like New', 'location', 'Ottawa', 'description', 'Set of 4, winter tires.')}; ...
   {'U0005', 'Liam Johnson', '4318765432', 'Barrie', struct('name', 'Samsung Galaxy S10', 'category', 'Electronics', 'price', '400', 'condition', 'Good', 'location', 'Barrie', 'description', '128GB, minor wear.')}; ...
   {'U0006', 'Olivia White', '3062347890', 'Ottawa', struct('name', 'Nike Sneakers', 'category', 'Clothing', 'price', '80', 'condition', 'Fair', 'location', 'Ottawa', 'description', 'White, size 9, worn a few times.')}; ...
   {'U0007', 'James Harris', '9024567890', 'Toronto', struct('name', 'Sofa Set', 'category', 'Furniture', 'price', '500', 'condition', 'Good', 'location', 'Toronto', 'description', '3-piece set, gray fabric.')}; ...
   {'U0008', 'Charlotte Clark', '6049871234', 'Markham', struct('name', 'Car Battery', 'category', 'Auto Care', 'price', '100', 'condition', 'New', 'location', 'Markham', 'description', 'Fits most sedans, 12V.')}; ...
   {'U0009', 'William Allen', '2896543210', 'Mississauga', struct('name', 'MacBook Air 2019', 'category', 'Electronics', 'price', '750', 'condition', 'Excellent', 'location', 'Mississauga', 'description', '256GB SSD, very light use.')}; ...
   {'U0010', 'Mia Young', '9052345678', 'Toronto', struct('name', 'Winter Coat', 'category', 'Clothing', 'price', '100', 'condition', 'Like New', 'location', 'Toronto', 'description', 'North Face, size L, very warm.')}; ...
   {'U0011', 'Lucas Adams', '4187654321', 'Markham', struct('name', 'Office Chair', 'category', 'Furniture', 'price', '150', 'condition', 'Excellent', 'location', 'Markham', 'description', 'Ergonomic, black leather.')}; ...
   {'U0012', 'Amelia Lewis', '5198765432', 'Brampton', struct('name', 'Car Jack', 'category', 'Auto Care', 'price', '75', 'condition', 'Good', 'location', 'Brampton', 'description', 'Hydraulic, 3-ton capacity.')}; ...
   {'U0013', 'Benjamin Walker', '2265437890', 'Mississauga', struct('name', 'Sony PlayStation 4', 'category', 'Electronics', 'price', '300', 'condition', 'Fair', 'location', 'Mississauga', 'description', '500GB, includes one controller.')}; ...
   {'U0014', 'Ella Scott', '3062345678', 'Toronto', struct('name', 'Denim Jeans', 'category', 'Clothing', 'price', '40', 'condition', 'Good', 'location', 'Toronto', 'description', 'Levi’s, size 32, no stains.')}; ...
   {'U0015', 'Henry King', '7098765432', 'Ottawa', struct('name', 'Bookshelf', 'category', 'Furniture', 'price', '120', 'condition', 'Good', 'location', 'Ottawa', 'description', '5 shelves, dark brown wood.')}; ...
   {'U0016', 'Evelyn Green', '6135432109', 'Mississauga', struct('name', 'Car Wax Kit', 'category', 'Auto Care', 'price', '30', 'condition', 'New', 'location', 'Mississauga', 'description', 'Includes polish and microfiber cloth.')}; ...
   {'U0017', 'Daniel Hall', '8072345678', 'Barrie', struct('name', 'Google Pixel 5', 'category', 'Electronics', 'price', '550', 'condition', 'Like New', 'location', 'Barrie', 'description', '128GB, perfect condition.')}; ...
   {'U0018', 'Sofia Turner', '8198765432', 'Mississauga', struct('name', 'Running Shoes', 'category', 'Clothing', 'price', '70', 'condition', 'Good', 'location', 'Mississauga', 'description', 'Adidas, size 10, lightly used.')}; ...
   {'U0019', 'David Carter', '6137654321', 'Kingston', struct('name', 'Dining Chairs Set', 'category', 'Furniture', 'price', '200', 'condition', 'Excellent', 'location', 'Kingston', 'description', 'Set of 4, modern design.')}; ...
   {'U0020', 'Lily Mitchell', '7056543210', 'Brampton', struct('name', 'Car Dashboard Camera', 'category', 'Auto Care', 'price', '120', 'condition', 'New', 'location', 'Brampton', 'description', '1080p HD, night vision.')}; ...
   {'U0021', 'Joseph Perez', '4185432109', 'Brampton', struct('name', 'iPad Air', 'category', 'Electronics', 'price', '450', 'condition', 'Fair', 'location', 'Brampton', 'description', '64GB, minor dents.')}; ...
   {'U0022', 'Emily Roberts', '5068765432', 'Mississauga', struct('name', 'Leather Handbag', 'category', 'Clothing', 'price', '90', 'condition', 'Good', 'location', 'Mississauga', 'description', 'Brown leather, spacious.')}; ...
   {'U0023', 'Matthew Collins', '8075432109', 'Toronto', struct('name', 'TV Stand', 'category', 'Furniture', 'price', '150', 'condition', 'Excellent', 'location', 'Toronto', 'description', 'Fits up to 55-inch TV.')}; ...
   {'U0024', 'Ava Stewart', '4037654321', 'Markham', struct('name', 'Engine Oil', 'category', 'Auto Care', 'price', '45', 'condition', 'New', 'location', 'Markham', 'description', '5L synthetic oil.')}; ...
   {'U0025', 'Oliver Ramirez', '8678765432', 'Barrie', struct('name', 'GoPro Hero 9', 'category', 'Electronics', 'price', '300', 'condition', 'Good', 'location', 'Barrie', 'description', '4K recording, waterproof.')}; ...
   {'U0026', 'Chloe Foster', '8675432109', 'Mississauga', struct('name', 'Winter Boots', 'category', 'Clothing', 'price', '100', 'condition', 'Like New', 'location', 'Mississauga', 'description', 'Columbia, size 8.')}; ...  
   {'U0027', 'David Brown', '4455667788', 'Toronto', struct('name','2017 Subaru Outback', 'category','Automotive', 'price', '18000', 'condition', 'Excellent', 'location', 'Toronto', 'Description', 'AWD, great for winter driving.')}; ...
   {'U0028', 'Sophia Wilson', '3344556677', 'Barrie', struct('name','2015 Volkswagen Golf', 'category','Automotive', 'price', '10500', 'condition', 'Good', 'location', 'Barrie', 'Description', 'Hatchback, sporty, fuel-efficient.')}; ...
   {'U0029', 'James Anderson', '2233445566', 'Mississauga', struct('name','2020 Tesla Model 3', 'category','Automotive', 'price', '27000', 'condition', 'Excellent', 'location', 'Mississauga', 'Description', 'Fully electric, eco-friendly, smooth drive.')}; ...
   {'U0030', 'Olivia Martinez', '1122334455', 'Toronto', struct('name','2016 Honda CR-V', 'category','Automotive', 'price', '16500', 'condition', 'Good', 'location', 'Toronto', 'Description', 'Compact SUV, fuel-efficient, AWD.')}; ...
   }


% Counter for assigning unique user IDs, starting from 30.
idCounter = 30;

% Cell array to store items added to the shopping cart.
cart = {};

% Counter to keep track of the number of items in the cart.
cartCounter = 0;


% Save the initialized variables to 'userDataLists.mat' file.
save('userDataLists.mat',  'idCounter', 'existData' , 'cart', 'cartCounter')


